BATCH_SIZE: 8
EPOCHS: 300
IMG_DIR: D:/ADPT-TOOLBOX-main/code
IMG_SIZE_H: 480
IMG_SIZE_H_ori: 540
IMG_SIZE_W: 640
IMG_SIZE_W_ori: 960
JSON: D:/ADPT-TOOLBOX-main/code/output_frames/merged_annotations.json
NUM_KEYPOINT: 16
TrainingFraction: 0.7
Tranfer_LR: 1e-3
WARMUP_EPOCHS: 10
alpha: 1e-5
bodyparts:
- nose
- left_ear
- right_ear
- neck
- left_front_limb
- right_front_limb
- left_hind_limb
- right_hind_limb
- left_front_claw
- right_front_claw
- left_hind_claw
- right_hind_claw
- back
- root_tail
- mid_tail
- tip_tail
centre: 3#Index of body center keypoint.
channels: 3
delta: 0.025
early_stop: True #It should be set as 'False' for multi-animal tracking
global_scale: 0.5
initial_learning_rate: 1e-3
initial_weight: None
num_classes: 1
shuffle_num: 117481
skeleton:
- (0,1)
- (0,2)
- (1,2)
- (2,3)
- (1,3)
- (3,4)
- (3,5)
- (4,5)
- (4,6)
- (4,8)
- (5,7)
- (6,7)
- (5,9)
- (6,10)
- (7,11)
- (3,12)
- (4,12)
- (5,12)
- (6,12)
- (7,12)
- (13,12)
- (7,13)
- (6,13)
- (13,14)
- (14,15)
variation: 17 / 8
